name: dart_server
description: A starting point for Dart libraries or applications.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

resolution: workspace

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  audioplayers: ^6.4.0
  flutter:
    sdk: flutter

  kobayashi_maru: ^0.1.0

  shelf: ^1.4.2
  shelf_web_socket: ^3.0.0
  universal_platform: ^1.1.0
  # path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^5.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/sounds/
    - assets/sounds/files/weapons/
